From nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

RUN sed -i 's#http://archive.ubuntu.com#http://mirrors.cloud.tencent.com#g' /etc/apt/sources.list

RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-get update && apt-get install -y --no-install-recommends wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb && rm -f cuda-keyring_1.0-1_all.deb

RUN apt-get update && apt-get install vim wget axel net-tools iputils-ping telnet curl bzip2 zip libxml2 gcc kmod pciutils -y && apt-get clean

RUN wget https://mirrors.bfsu.edu.cn/anaconda/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh \
&& bash Miniconda3-py38_4.9.2-Linux-x86_64.sh -b -p /opt/conda \
&& rm -f Miniconda3-py38_4.9.2-Linux-x86_64.sh

ENV PATH=/opt/conda/bin:${PATH}

RUN /bin/bash -c 'conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ \
&& conda config --set show_channel_urls yes'

RUN /bin/bash -c 'conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/ \
&& conda config --set show_channel_urls yes'

RUN pip config set global.index-url http://mirrors.cloud.tencent.com/pypi/simple \
&& pip config set global.trusted-host mirrors.cloud.tencent.com

RUN /bin/bash -c 'conda create -n jupyter python=3.8 jupyterlab notebook jupyterhub --yes'

SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 --yes

RUN mkdir -p /opt/ml/code \
 && mkdir -p /opt/ml/input/config \
 && mkdir -p /opt/ml/input/data \
 && mkdir -p /opt/ml/input/pretrain_model \
 && mkdir -p /opt/ml/model  \
 && mkdir -p /opt/ml/checkpoint \
 && mkdir -p /opt/ml/output  \
 && mkdir -p /opt/ml/summary \
 && mkdir -p /opt/ml/failure \
 && mkdir -p /opt/ml/entry

WORKDIR /opt/ml/code

CMD ["/bin/bash"]