From nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04

RUN sed -i 's#http://archive.ubuntu.com#http://mirrors.cloud.tencent.com#g' /etc/apt/sources.list

RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-get update && apt-get install -y --no-install-recommends wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb && rm -f cuda-keyring_1.0-1_all.deb

RUN apt update && apt install vim wget axel net-tools iputils-ping telnet curl bzip2 zip libxml2 gcc kmod pciutils -y && apt-get clean

RUN wget https://mirrors.bfsu.edu.cn/anaconda/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh \
&& bash Miniconda3-py38_4.9.2-Linux-x86_64.sh -b -p /opt/conda \
&& rm -f Miniconda3-py38_4.9.2-Linux-x86_64.sh

ENV PATH=/opt/conda/bin:$PATH

RUN /bin/bash -c 'conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ \
&& conda config --set show_channel_urls yes'

# pytorch
RUN /bin/bash -c 'conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/ \
# 安装时PyTorch，官网给的安装命令需要去掉最后的-c pytorch，才能使用清华源
# conda-forge
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/ \
# msys2
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/ \
# bioconda
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/ \
# menpo
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/ \
# 设置搜索时显示通道地址
&& conda config --set show_channel_urls yes'


RUN pip config set global.index-url http://mirrors.cloud.tencent.com/pypi/simple \
&& pip config set global.trusted-host mirrors.cloud.tencent.com

RUN /bin/bash -c 'conda create -n jupyter python=3.8 --yes'
# 用于激活环境，conda activate命令无效
SHELL ["/bin/bash", "-c"]

RUN exec bash \
 && . /root/.bashrc \
 && conda init bash \
 && conda activate jupyter \
 && conda install jupyterlab notebook jupyterhub

RUN mkdir -p /opt/ml/code \
 && mkdir -p /opt/ml/input/config \
 && mkdir -p /opt/ml/input/data \
 && mkdir -p /opt/ml/input/pretrain_model \
 && mkdir -p /opt/ml/model  \
 && mkdir -p /opt/ml/checkpoint \
 && mkdir -p /opt/ml/output  \
 && mkdir -p /opt/ml/summary \
 && mkdir -p /opt/ml/failure \
 && mkdir -p /opt/ml/entry

RUN conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit==10.2