From ubuntu:20.04

RUN sed -i 's#http://archive.ubuntu.com#http://mirrors.cloud.tencent.com#g' /etc/apt/sources.list

RUN apt-get update && apt-get install vim wget axel net-tools iputils-ping telnet curl bzip2 zip libxml2 gcc kmod pciutils -y && apt-get clean

RUN apt install python3 python3-pip -y